Repository nanvix/kernel, pull requests merged in 2018-12, with the labels that each got.

#20 Enhancement: GDB Confirm Off, Quit If Connection Lost
  .gdbinit
Labels: enhancement

#19 [i386] Bug Fix: Bad Kernel Page Pool Size
  include/target/ibm/pc.h
Labels: bug

#22 Bug Fix: i386 Boot Symbols
  src/kernel/hal/arch/i386/boot.S
Labels: bug, i386-pc

#23 [i386] Bug Fix: Bad PDE Get
  include/arch/i386/mmu.h
Labels: bug, i386-pc

#25 [i386] Enhancement: Improving MMU Interface
  include/arch/i386/mmu.h
Labels: enhancement

#24 [i386-pc] Bug Fix: Bad Memory Sizes
  include/target/ibm/pc.h
Labels: bug

#26 [hal] Bug Fix: Missing Mandatory Memory Constants
  include/nanvix/hal/target.h
Labels: bug

#27 Enhancement: Improving Build Options
  build/makefile.i386-pc
  src/makefile
Labels: enhancement, i386-pc

#28 Bug Fix: Bad Debug Release Build
  src/makefile
Labels: bug

#34 [k1b] Bug Fix: Endless Comment
  src/kernel/hal/arch/k1b/hooks.S
Labels: bug

#37 Bug Fix: Bad Kernel Page Pool Address Checking
  src/kernel/mm/mm.c
Labels: bug

#38 Bug Fix: Bad Invalid Free Frame Test
  src/kernel/test/mm.c
Labels: bug

#72 Bug Fix: Avoid Linking LibGCC with the Kernel
  src/kernel/klib/kvsprintf.c
Labels: bug, confirmed

#77 Enhancement k1b Virtual Exceptions
  include/arch/k1b/excp.h
  src/kernel/hal/arch/k1b/excp.c
Labels: enhancement

#78 [k1b] Enhancement: Source Tree Refactor
  include/arch/k1b/core.h
  include/arch/k1b/mmu.h
  src/kernel/hal/arch/k1b/core.c
  src/kernel/hal/arch/k1b/mmu.c
  src/kernel/hal/arch/k1b/mppa256.h
  src/kernel/hal/arch/k1b/setup.c
  src/kernel/init/main.c
  src/kernel/sys/exit.c
Labels: enhancement

#79 [hal] Enhancement: Improving Core Interface
  include/arch/i386/core.h
  include/arch/k1b/core.h
  include/nanvix/hal/core.h
  include/nanvix/hal/target.h
  src/kernel/dev/klog.c
  src/kernel/hal/clock.c
  src/kernel/init/main.c
  src/kernel/pm/thread.c
  src/test/mppa256/main.c
Labels: enhancement

#81 Enhancement: Exception Interface Check
  include/arch/i386/excp.h
  include/arch/k1b/excp.h
  include/nanvix/hal/target.h
  src/kernel/hal/arch/i386/excp.c
  src/kernel/hal/arch/k1b/excp.c
  src/kernel/mm/page.c
  src/kernel/test/hal.c
Labels: enhancement, i386-pc, mppa256
