Repository nanvix/kernel, pull requests merged in 2019-02, with the labels that each got.

#96 [or1k] Bug Fix: Initial TLB Handler
  src/kernel/hal/arch/or1k/setup.c
Labels: bug, confirmed

#110 [k1b] Bug Fix: Misaligned Root Page Table
  src/kernel/hal/arch/k1b/mmu.c
Labels: bug, mppa256

#106 Enhancement k1b memory layout
  build/mppa256/linker/k1bdp/link.ld
  build/mppa256/linker/k1bio/link.ld
  include/arch/k1b/elf.h
  include/target/kalray/mppa256.h
  src/kernel/hal/arch/k1b/_core.S
  src/kernel/hal/arch/k1b/mmu.c
  src/kernel/mm/mm.c
Labels: enhancement, mppa256

#111 Bug Fix: All Exiting Threads Unblock
  src/kernel/pm/thread.c
Labels: bug

#112 Enhancement k1b context
  include/arch/k1b/context.h
  include/arch/k1b/regs.h
  src/kernel/hal/arch/k1b/hooks.S
  src/kernel/test/hal/hal.c
Labels: enhancement, mppa256

#116 Bugfix k1b context
  include/arch/k1b/context.h
  src/kernel/hal/arch/k1b/hooks.S
Labels: bug, mppa256

#118 [k1b] Bug Fix: Dispatch Virtual Exceptions
  src/kernel/hal/arch/k1b/excp.c
Labels: bug, mppa256

#120 [or1k] Feature: UART 8250 Support
  include/arch/or1k/mmu.h
  include/driver/8250.h
  include/target/or1k/pc.h
  src/kernel/build/makefile.or1k-pc
  src/kernel/dev/stdout/8250.c
  src/kernel/hal/arch/or1k/boot_code.S
  src/kernel/hal/arch/or1k/boot_data.S
  src/kernel/hal/arch/or1k/excp.c
  src/kernel/hal/arch/or1k/tlb.c
  src/kernel/mm/page.c
Labels: feature, or1k-qemu

#121 [k1b] Enhancement: Kernel Exception Stack
  include/nanvix/const.h
  src/kernel/hal/arch/k1b/ivt.c
  src/kernel/init/main.c
Labels: enhancement, mppa256

#122 [k1b] Bug Fix: Bad Function Epilogue
  include/arch/k1b/regs.h
  include/nanvix/thread.h
Labels: bug

#123 Enhancement: Exception Forwarding
  include/arch/k1b/excp.h
  include/arch/or1k/excp.h
  src/kernel/hal/arch/k1b/excp.c
  src/kernel/hal/arch/or1k/excp.c
  src/kernel/mm/page.c
Labels: enhancement, mppa256, or1k-qemu

#130 [or1k] Bug Fix: Calling Notify When Core Is Already Locked
  src/kernel/hal/arch/or1k/core.c
Labels: bug, or1k-qemu

#131 [or1k] Bug Fix: Cyclic Dependency
  src/kernel/hal/arch/or1k/ompic.c
  src/kernel/hal/arch/or1k/tlb.c
Labels: bug

#132 [or1k] Bug Fix: Errno Definition
  src/libs/makefile
  src/libs/nanvix/errno.c
Labels: bug
