Repository nanvix/kernel, pull requests merged in 2023-11, with the labels that each got.

#357 [kernel] F: Log subsystem
  include/nanvix/kernel/log.h
  src/kernel/Makefile
  src/kernel/log/log.c
Labels: feature

#358 [kernel] B: Bad Quantum Length
  src/kernel/pm/thread.c
Labels: bug

#359 [libnanvix] B: Never Inline Kernel Calls
  src/libnanvix/src/kcall/mod.rs
Labels: bug

#360 Enhancement kernel mm
  include/nanvix/kernel/hal/arch/x86/memory.h
  scripts/run.sh
Labels: enhancement

#361 [kernel] B: Wrong Number of Root Page Tables
  src/kernel/mm/memory.c
Labels: bug

#362 [kernel] E: Load Multiple Servers
  src/kernel/kmain.c
Labels: enhancement

#363 Enhancement kernel mm
  build/x86/kernel.ld
  build/x86/user.ld
  include/nanvix/kernel/hal/memory.h
  include/nanvix/kernel/mm/memory.h
  src/kernel/mm/memory.c
  src/libnanvix/src/memory/constants.rs
  src/servers/init/test.rs
Labels: enhancement
