Repository nanvix/kernel, pull requests merged in 2024-01, with the labels that each got.

#364 Enhancement pm thread
  include/nanvix/kernel/kcall.h
  include/nanvix/kernel/pm.h
  include/nanvix/kernel/pm/cond.h
  include/nanvix/kernel/pm/process.h
  src/kernel/elf.c
  src/kernel/hal/arch/hooks.S
  src/kernel/kmain.c
  src/kernel/pm/cond.c
  src/kernel/pm/pm.c
  src/kernel/pm/process.c
  src/kernel/pm/semaphore.c
  src/kernel/pm/thread.c
Labels: enhancement

#372 Enhancement doc todos
  include/arch/x86/mmu.h
  include/asm/x86.S
  include/nanvix/kernel/hal/arch/x86/spinlock.h
  include/nanvix/kernel/hal/cpu.h
  src/kernel/hal/arch/ctx.c
  src/kernel/hal/arch/mmu.c
  src/kernel/kcall/frame.c
  src/kernel/kcall/vmem.c
  src/kernel/kmain.c
  src/kernel/lib/bitmap.c
  src/kernel/lib/kprintf.c
  src/kernel/mm/memory.c
  src/kernel/mm/upool/mod.c
  src/kernel/mm/vmem/mod.c
  src/libdev/uart.c
Labels: documentation

#373 [kernel] Bad Log Macro
  include/nanvix/kernel/log.h
Labels: bug

#374 Bugfix kernel mm
  src/kernel/hal/arch/mmu.c
  src/kernel/mm/memory.c
Labels: bug

#376 Enhancement kernel mm
  include/nanvix/kernel/mm.h
  src/kernel/mm/vmem/mod.c
Labels: enhancement

#377 Enhancement kernel pm
  include/nanvix/kernel/pm/process.h
  src/kernel/kmain.c
  src/kernel/pm/process.c
Labels: enhancement

#378 Enhancement build rust
  Makefile
  rust-toolchain
  rustfmt.toml
  src/Makefile
  src/libnanvix/Makefile
  src/libnanvix/rust-toolchain
  src/libnanvix/rustfmt.toml
  src/servers/init/rust-toolchain
  src/servers/init/rustfmt.toml
  src/servers/test/rust-toolchain
  src/servers/test/rustfmt.toml
Labels: enhancement

#381 [build] B: Setup QEMU 8.1.0
  scripts/setup/qemu.sh
Labels: bug

#386 [kernel] F: Mailbox Abstraction
  include/nanvix/kernel/ipc/mailbox.h
  src/kernel/Makefile
  src/kernel/ipc/mailbox/mailbox.c
  src/kernel/ipc/mailbox/mailboxes.c
  src/kernel/ipc/mailbox/mod.c
  src/kernel/ipc/mailbox/mod.h
  src/kernel/ipc/mailbox/omailboxes.c
  src/kernel/kmain.c
Labels: feature

#396 [build] B: Increase DOT_GRAPH_MAX_NODES parameter
  doc/kernel.doxygen
Labels: bug

#394 Fix attempt of `process_exit()` causing a use after free
  src/kernel/pm/process.c
Labels: bug

#390 Feature kernel semaphore syscalls
  include/nanvix/kernel/kcall.h
  src/kernel/Makefile
  src/kernel/kcall/mod.c
  src/kernel/kcall/mod.h
  src/kernel/kcall/sem/semctl.c
  src/kernel/kcall/sem/semget.c
  src/kernel/kcall/sem/semop.c
  src/libnanvix/src/kcall/mod.rs
  src/libnanvix/src/pm/mod.rs
  src/servers/test/src/test.rs
Labels: feature

#397 [libcore] Adding strncmp
  include/nanvix/libcore.h
  src/libcore/strncmp.c
Labels: enhancement
